### ISSUE TITLE
maxLifeDuration prematurely closes the connection

### ISSUE THREAD

**Issue by gillmk** [ProcessOut/grpc-go-pool#14]
If MaxLifeDuration is set, connection was only reused once and gets closed early as during cloning of ClienConn https://github.com/processout/grpc-go-pool/blob/08356189070e8e896f90ac772a295f18718d0de0/pool.go#L205, timeInitiated was never copied, hence the following condition 
 ```
if maxDuration > 0 && c.timeInitiated.Add(maxDuration).Before(time.Now()) {
 		c.Unhealthy()
 	}
```
gets true next time the Close(). 

Fix is to copy the timeInitiated from the original object to the clone.Can someone please review https://github.com/processout/grpc-go-pool/pull/12 for the fix? Thanks

**Comment by gillmk** [comment]
Hello @manuel-huez, @AgrimPrasad, Can this issue and the mentioned PR be reviewed please? Thanks.

**Comment by manuel-huez** [comment]
Hey @gillmk, thanks a lot for your contribution! I reviewed your PR and merged it. Closing this now
