### ISSUE TITLE
Does the pool support blocking get and other advanced features in Vitess pools?

### ISSUE THREAD

**Issue by iiinsomnia** [ProcessOut/grpc-go-pool#15]

**Comment by manuel-huez** [comment]
Yes, a `Get(ctx)` will block until a connection becomes available in the pool. Alternatively, if you set a Deadline in the context passed as a parameter to `Get(ctx)`, you can prevent deadlocks in your application by having `Get(ctx)` return a timeout error if it waits for too long.

**Comment by iiinsomnia** [comment]
thanks a lot !
