### ISSUE TITLE
Zombie connections when calling Close() after marking connection as unhealthy

### ISSUE THREAD

**Issue by stoccoPismo** [ProcessOut/grpc-go-pool#3]
We discovered that by marking a connection unhealthy in the pool the grpc connection is not closed after calling the wrapper Close() method. This can lead to multiple "zombie" connections alive and  since the grpc reuses alive connections this will make the subsequent requests to fail.

I'v made a pr with the fix, I just cant push my branch to open it

**Comment by carl-leopard** [comment]
Can you show me how you fix it?  I am searching for a grpc  pool to use in my project.

**Comment by stoccoPismo** [comment]
It is on the Close() method, if the conn is unhealthy we should also close the grpc connection before marking as nil.

We need this fix asap, I dont want to fork the project :(

```
// Close returns a ClientConn to the pool. It is safe to call multiple time,
// but will return an error after first time
func (c *ClientConn) Close() error {
	if c == nil {
		return nil
	}
	if c.ClientConn == nil {
		return ErrAlreadyClosed
	}
	if c.pool.IsClosed() {
		return ErrClosed
	}

	// We're cloning the wrapper so we can set ClientConn to nil in the one
	// used by the user
	wrapper := ClientConn{
		pool:       c.pool,
		ClientConn: c.ClientConn,
		timeUsed:   time.Now(),
	}
	if c.unhealthy {
		wrapper.ClientConn.Close()
		wrapper.ClientConn = nil
	}
	select {
	case c.pool.clients <- wrapper:
		// All good
	default:
		return ErrFullPool
	}

	c.ClientConn = nil // Mark as closed
	return nil
}
```

**Comment by manuel-huez** [comment]
Thanks a lot for reporting this issue! I've gone ahead and committed that change.
We should probably write some tests covering that as well, but I don't have much time to work on this right now.

Just some bit of feedback on reporting issues though: you can open PRs by forking the package :) If you have time to write a test coverage that change, that'd be great!
Thanks again.

**Comment by carl-leopard** [comment]
Ths. I don't find function to put conn to pool.  In this case,  it doesn't need to do so or i should write it myself?
