### ISSUE TITLE
I don't find a function to put conn to pool when business finished.

### ISSUE THREAD

**Issue by carl-leopard** [ProcessOut/grpc-go-pool#4]
Ths. I don't find a function to put conn to pool  when business finished. In this case, it doesn't need to do so or i should write it myself?

**Comment by manuel-huez** [comment]
Hi Carl, thanks for reaching out. I think what you want is to call `Close` on your `ClientConn` when you want to return the conn to the pool. https://godoc.org/github.com/processout/grpc-go-pool#ClientConn.Close

**Comment by carl-leopard** [comment]
Oh, i simple thought function close is to close the conn. Ths.
