### ISSUE TITLE
maxLifeDuration should check after time initiated

### ISSUE THREAD

**Issue by dorkolog** [ProcessOut/grpc-go-pool#7]
Not sure if I got it right, but for my understanding - setting ```maxLifeDuration``` should result in unhealthy connection only if its ```After(time.Now())```. should this be fixed ?

https://github.com/processout/grpc-go-pool/blob/6f31a97b80d10a7bbefa392828d1a7f1b50a40fa/pool.go#L194

**Comment by dorkolog** [comment]
@manuel-huez can you please respond ?

**Comment by manuel-huez** [comment]
Hi @dorkolog— thanks for reaching out!
The logic is correct as is. I pushed a change that should clarify the logic with some comments, and an additional test to prove my point.
https://github.com/processout/grpc-go-pool/pull/8

Feel free to review it & reach out if it doesn't answer your question!

**Comment by dorkolog** [comment]
@manuel-huez thanks for your clarification. for some reason this tricked me.
please review my commit - I reversed the if order and added a similar test to idletimeout

**Comment by dorkolog** [comment]
@manuel-huez thank you for your time clarifying it. my fault.
I opened another PR that also adds a test for ```idleTimeout```, and changed the if order for better readability. hope you'll like it

**Comment by manuel-huez** [comment]
Closing it now that PRs have been merged. Thanks!
